### ISSUE TITLE
Renaming it to awesome-parcel? 

### ISSUE THREAD

**Issue by vinayakkulkarni** [parcel-bundler/examples#2]
All big frameworks have an awesome-repo inspired from [this](https://github.com/sindresorhus/awesome)

This could be renamed to awesome-parcel since it'll have all different frameworks know-how at one place...

**Comment by omouse** [comment]
That's not a bad idea for SEO purposes though it would also need a section for articles/tutorials related to Parcel.

**Comment by devongovett** [comment]
the intention of this repo is for actual code examples, not just links to other places.

**Comment by vinayakkulkarni** [comment]
Glad to see [Awesome-Parcel](https://github.com/parcel-bundler/awesome-parcel)
