### ISSUE TITLE
React dist output wont load/isn't working? 

### ISSUE THREAD

**Issue by azeznassar** [parcel-bundler/examples#23]
The example will load on localhost but doesn't open when trying from 'dist/index.html'. Loading it from here wont work after npm run build or npm start. I am also having this problem with other React example with Parcel, whats causing parcels bundled files not to work from dist but work on localhost?

**Comment by DeMoorJasper** [comment]
dist should be opened with a server behind it. Otherwise the `/...` paths it creates inside html file will throw 404s
